# Generated by Django 2.2.6 on 2019-12-27 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('content', models.TextField(max_length=500, verbose_name='Content')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('is_with_poll', models.BooleanField(default=False, verbose_name='Is with poll')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date_begin', models.DateTimeField(verbose_name='Date begin')),
                ('date_end', models.DateTimeField(verbose_name='Date end')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='events.Room', verbose_name='Address')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('date_begin',),
                'get_latest_by': ('date_begin',),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[(1, 'Confused'), (2, 'Accepted'), (3, 'Rejected')], default=1, verbose_name='Choice')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='events.Event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
