# Generated by Django 2.2.6 on 2019-11-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191119_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='applicants.Applicant'),
        ),
    ]
