# Generated by Django 2.2.6 on 2019-11-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191119_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='events.Event'),
        ),
    ]
