# Generated by Django 2.2.6 on 2019-11-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191119_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='applicants.Applicant'),
        ),
    ]
