# Generated by Django 2.2.6 on 2019-11-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20191122_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.IntegerField(choices=[(1, 'Confused'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
    ]
