# Generated by Django 2.2.6 on 2019-12-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191123_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'get_latest_by': ('date',), 'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='event',
            name='is_with_poll',
            field=models.BooleanField(default=False),
        ),
    ]
