# Generated by Django 2.2.6 on 2019-12-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(error_messages={'message': 'User with this email already exists.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
