# Generated by Django 2.2.6 on 2019-12-15 01:52
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.contrib.auth.models import User, Group, Permission
from applicants.models import Applicant
from application_info.models import Department
from events.models import Event, Room, Book, Choice


def add_permission(group_object, permission_model):
    content_type = ContentType.objects.get_for_model(permission_model)
    permissions = Permission.objects.filter(content_type=content_type)
    for permission in permissions:
        group_object.permissions.add(permission)


def create_project_manager_admin_group(apps, schema_editor):
    pm_admin_group = Group.objects.create(name='PM Admin')
    add_permission(pm_admin_group, Event)
    add_permission(pm_admin_group, Room)
    add_permission(pm_admin_group, Book)
    add_permission(pm_admin_group, Choice)
    add_permission(pm_admin_group, Group)
    add_permission(pm_admin_group, Department)
    add_permission(pm_admin_group, Applicant)


def create_team_leader_admin_group(apps, schema_editor):
    tl_admin_group = Group.objects.create(name='TL Admin')
    add_permission(tl_admin_group, Event)
    add_permission(tl_admin_group, Room)
    add_permission(tl_admin_group, Book)
    add_permission(tl_admin_group, Applicant)
    add_permission(tl_admin_group, Choice)


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_project_manager_admin_group),
        migrations.RunPython(create_team_leader_admin_group),
    ]
