# Generated by Django 2.2.6 on 2019-12-27 21:51

from django.db import migrations
from application_info.models import Department


def create_departament(apps, schema_editor):
    Department.objects.create(name='Android mobile development')
    Department.objects.create(name='Backend Python')
    Department.objects.create(name='Backend C#')
    Department.objects.create(name='Backend Kotlin/Java')
    Department.objects.create(name='iOS mobile development')
    Department.objects.create(name='Web Frontend')
    Department.objects.create(name='Design')
    Department.objects.create(name='Game Development, AR/VR')
    Department.objects.create(name='Project Management')
    Department.objects.create(name='Backend NodeJS')


class Migration(migrations.Migration):

    dependencies = [
        ('application_info', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_departament),
    ]
